### ISSUE TITLE
Report Error in Google webmasters tool

### ISSUE THREAD

**Issue by hqin2013** [o/sitemap-php#8]
hi,

I use this script to general a sitemap(http://www.top10selling.net/sitemap.xml),but get error:

![s](https://cloud.githubusercontent.com/assets/3657122/7427767/32b79c4c-f015-11e4-81d3-c3d094fb15e4.PNG)

regards
hqin

**Comment by ericmuigai** [comment]
I think this is due to urlset no tbeing closed.

**Comment by ericmuigai** [comment]
See this https://github.com/o/sitemap-php/compare/master...ericmuigai:patch-1
Will solve it

**Comment by o** [comment]
Hi @ericmuigai and hi @hqin2013,

Sorry for my late answer, as described in README, you need to call `createSitemapIndex()` function for closing urlset tag. @ericmuigai library already have this functionality whilst creating sitemap index. Thanks for the patch, but it's not necessary.
